INSERT INTO CARD VALUES(1, 'brainstorm', 4);
INSERT INTO CARD VALUES(2, 'ponder', 4);
INSERT INTO CARD VALUES(3, 'preordain', 4);
INSERT INTO CARD VALUES(4, 'cloudpost', 4);
INSERT INTO CARD VALUES(5, 'glimmerpost', 4);

INSERT INTO DECK VALUES(1, 'sneakAndShow');
INSERT INTO DECK VALUES(2, 'greenPost');

INSERT INTO DECK_CARDS VALUES(1, 1);
INSERT INTO DECK_CARDS VALUES(1, 2);
INSERT INTO DECK_CARDS VALUES(1, 3);
INSERT INTO DECK_CARDS VALUES(2, 4);
INSERT INTO DECK_CARDS VALUES(2, 5);

INSERT INTO PLAYER VALUES('Hawig', 1);
INSERT INTO PLAYER VALUES('Nick', 2);